Metrics/AbcSize:
  Enabled: true
  Max: 30

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    # bundled gems
    - 'vendor/**/*'
    # package testing gems
    - 'testing/vendor/**/*'
    # binstubs files
    - 'bin/*'

Style/FormatStringToken:
  Exclude:
    - 'config/routes.rb'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'app/helpers/meta_tags_helper.rb'
