Metrics/AbcSize:
  Enabled: true
  Max: 30

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - 'config/routes.rb'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'app/helpers/meta_tags_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

AllCops:
  Exclude:
    # bundled gems
    - 'vendor/**/*'
    # package testing gems
    - 'testing/vendor/**/*'
    # binstubs files
    - 'bin/*'


