exclude:
  - 'app/views/curriculum_vitae/index.html.slim'
  - 'app/views/layouts/head/_ascii_art.html.slim'
  - 'app/views/layouts/head/_assets.html.slim'
  - 'app/views/layouts/head/_meta.html.slim'
  - 'app/views/layouts/tracking/_google_analytics.html.slim'

linters:
  LineLength:
    max: 80
