meta_title: "Sami BEN ABBES | Développeur Web Ruby On Rails"
meta_description: "Présentation de mon parcours et réalisations"
# FIXME
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@ProgrammingSam"
