meta_title: "Sami Ben Abbés | Développeur web full-stack"
meta_description: "Venez me découvrir !"
meta_image: "companies/programmingsam.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@ProgrammingSam"
