meta_title: "Sami Ben Abbés | Développeur web full-stack"
meta_description: "Venez me découvrir !"
# FIXME
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@ProgrammingSam"
